### ISSUE TITLE
Runner file

### ISSUE THREAD

**Issue by grandmaximum** [quarkiverse/quarkus-cucumber#3]
I don't have the option to perform a pull request (company restriction), so I write here instead. 

I added so the user have the option to define Steps and Feature files from a "runner file":

```
        runtimeOptionsBuilder.addGlue(URI.create("classpath:/" + stepsPath));
        runtimeOptionsBuilder.addFeature(FeatureWithLines.create(URI.create("classpath:/" + featurePath), Collections.emptyList()));

        if (tags != null)
        {
            for (String tag : tags)
            {
                runtimeOptionsBuilder.addTagFilter(TagExpressionParser.parse(tag));
            }
        }
````
And then implemented some setters:

```
   public void setGlue(String stepsPath)
    {
        this.stepsPath = stepsPath;
    }

    public void setFeature(String featurePath)
    {
        this.featurePath = featurePath;
    }

    public void setTag(String tags)
    {
        this.tags = Arrays.asList(tags.split("\\s*,\\s*"));
    }
```

in order for my "runner" class to look like this: 

```
@QuarkusTest
public class HelloRunner extends CucumberQuarkusTest
{
    @BeforeEach
    public void setup()
    {
        super.setGlue("ekn/information/hellocucumber");
        super.setFeature("Hello.feature");
        super.setTag("@smoke");
    }
}
```

I used the logics applied by @drubio-tlnd in [https://github.com/quarkusio/quarkus/issues/11045#issuecomment-769663017](url), which works if only one tag is used, but fails when there are many tags. Any idea why?

**Comment by grandmaximum** [comment]
@christophd It seems like the tag feature isn't really working. Whether or not I use tags and define them in the runner file, all the tests in the specified .feature-file is still run.

**Comment by christophd** [comment]
@grandmaximum let me check. how do you define the tags in the runner file?

**Comment by grandmaximum** [comment]
@RunWith(Cucumber.class)
@CucumberOptions(
        monochrome = true,
        features = "src/test/java/ekn/information/v/hello/Hello.feature",
        glue ="ekn.information.v.hello",
        tags = "@Saknar"
)
public class HelloRunnerQuarkiverse extends CucumberQuarkusTest
{
}

**Comment by christophd** [comment]
@grandmaximum thanks for reporting! Added the tag filtering support in #8

**Comment by grandmaximum** [comment]
@stuartwdouglas When are you planning on 0.4.0? Would be awesome if I could test the tag filtering.

**Comment by stuartwdouglas** [comment]
Here you go: https://github.com/quarkiverse/quarkus-cucumber/pull/9

Might take a bit to get into central.

**Comment by grandmaximum** [comment]
I ran into the same problem as mentioned in https://github.com/quarkusio/quarkus/issues/10435. 

When I run a steps method which uses a Restassured call I get the following error:

`      java.util.ServiceConfigurationError: org.apache.groovy.json.FastStringServiceFactory: org.apache.groovy.json.DefaultFastStringServiceFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at org.apache.groovy.json.internal.FastStringUtils$ServiceHolder.loadService(FastStringUtils.java:41)
	at org.apache.groovy.json.internal.FastStringUtils$ServiceHolder.<clinit>(FastStringUtils.java:33)
	at org.apache.groovy.json.internal.FastStringUtils.getService(FastStringUtils.java:55)
	at org.apache.groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:66)
	at org.apache.groovy.json.internal.CharBuf.addJsonEscapedString(CharBuf.java:341)
	at org.apache.groovy.json.internal.CharBuf.addJsonEscapedString(CharBuf.java:337)
	at groovy.json.JsonOutput.prettyPrint(JsonOutput.java:213)
	at groovy.json.JsonOutput$prettyPrint.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.path.json.JsonPrettifier.prettifyJson(JsonPrettifier.groovy:25)
	at io.restassured.internal.path.json.JsonPrettifier$prettifyJson.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.support.Prettifier.prettify(Prettifier.groovy:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at 
...`

The problem occures on the first class being loaded by RestAssures classloader. Is there a possible way around this or is RestAssured simply imcompatible with dynamic tests (@TestFactory) and thus quarkus-cucumber?

**Comment by christophd** [comment]
@bella-daza could you please open separate issue. Your problem seems to not be related to this one.
