### ISSUE TITLE
Execute cucumber test from custom module

### ISSUE THREAD

**Issue by deepakattarde-mcd** [quarkiverse/quarkus-cucumber#38]
Hi,

I am trying to execute cucumber test from custom/another module than test however facing issue.

```
java.lang.IllegalStateException: Unable to locate CDIProvider
	at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
	at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	at io.quarkiverse.cucumber.CucumberQuarkusTest$CdiObjectFactory.getInstance(CucumberQuarkusTest.java:184)
```
Not sure how to provide CDI to custom module. Any help on this would be appreciated.

I am able to execute cucumber test from test module however I want to separate it from JUnits.

Sample code:
[demo.zip](https://github.com/quarkiverse/quarkus-cucumber/files/8422382/demo.zip)

I am trying to execute cucumber test (health endpoint) against a running instance.

![image](https://user-images.githubusercontent.com/87499170/161866004-bd156d34-cbea-4e38-a88c-7ee9be71cb19.png)

**Comment by deepakattarde-mcd** [comment]
@stuartwdouglas, Would you be able to provide help on this?

**Comment by ozkanpakdil** [comment]
Hi, the problem is not about quarkus-cucumber but gradle :) check the file
[code-with-quarkus.tar.gz](https://github.com/quarkiverse/quarkus-cucumber/files/8525460/code-with-quarkus.tar.gz)

and here how it looks
![image](https://user-images.githubusercontent.com/604405/164324030-1dbe3861-2f98-4d25-b2ec-88c85fa6bc18.png)
